import Head from "next/head";
import styles from "../styles/Home.module.css";
import IngredientList from "../components/IngredientList/IngredientList";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Product Price Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="mb-6 text-lg">Product Price Caluculator</h1>
        <section>
          <IngredientList />
        </section>
      </main>
    </div>
  );
}
