import Head from "next/head";
import styles from "../styles/Home.module.css";
import FormItems from "../components/FormItems";
import Summary from "../components/Summary";
import { useReducer } from "react";
import formReducer from "../reducers/formReducer";

export default function Home() {
  const [formState, formDispatch] = useReducer(formReducer, {
    ingredient1: 0,
    ingredient2: 0,
    tax: 0,
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Product Price Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="mb-6 text-lg">Product Price Caluculator</h1>
        <section className="grid grid-cols-4 gap-4">
          <section className="">
            <FormItems formState={formState} formDispatch={formDispatch} />
          </section>
          <section className="">
            <Summary formState={formState} />
          </section>
        </section>
      </main>
    </div>
  );
}
