import Head from "next/head";
import styles from "../styles/Home.module.css";
import IngredientList from "../components/IngredientList/IngredientList";
import { useReducer } from "react";
import ingredientListReducer from "../components/IngredientList/reducers/ingredientListReducer";

export default function Home() {
  const [ingredientListState, ingredientListDispatch] = useReducer(
    ingredientListReducer,
    [
      {
        id: 0,
        ingredient: "",
        measurementType: "oz",
        purchaseSize: 0,
        averageCost: 0,
        costPerOunce: 0,
      },
    ]
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Product Price Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="mb-6 text-lg">Product Price Caluculator</h1>
        <section>
          <IngredientList />
        </section>
      </main>
    </div>
  );
}
